theme: jekyll-theme-slate
title: Derek Abdine
description: Cybersecurity researcher, entrepreneur, and engineer.
url: https://derekabdine.com

defaults:
  - scope:
      path: ""
    values:
      layout: default
